---
title: "c0182_vv"
date: 2020-09-18T01:27:56+99:00
draft: false
weight: 11821

---

### Log reference: <no value>

```
    loading [Config]:  ./tests/functests/upconfig.yml
    Main config:
                 Version -> 1.0.0
                  RefDir -> ./tests/functests
                 WorkDir -> cwd
              AbsWorkDir -> /up_project/up
                TaskFile -> c0182
                 Verbose -> vv
              ModuleName -> self
               ShellType -> /bin/sh
           MaxCallLayers -> 8
                 Timeout -> 3600000
     MaxModuelCallLayers -> 256
               EntryTask -> task
    work dir: /up_project/up
    -exec task: task
    loading [Task]:  ./tests/functests/c0182
    module: [self], instance id: [dev], exec profile: []
    Task1: [task ==> task:  ]
    -Step1: [: step 1 ]
    ~SubStep1: [print:  ]
    step 1
    ~SubStep2: [panic:  ]
     WARN: [manual panic] - [manual trigger a panic cmd]
    Step Finally:
    Recovered from: manual trigger a panic cmd
    -Step1: [close_file: ensure the opened file is closed
     ]
    cmd( 1):
    echo "close the file ....."
    
    -
    close the file .....
    
    -
     .. ok
    . ok
     WARN: [Rescued in step level, but not advised!] - [setting rescue to yes/true to continue is not recommended
    it is advised to locate root cause of the problem, fix it and re-run the task again
    it is the best practice to test the execution in your ci pipeline to eliminate problems rather than dynamically fix using rescue]
    -Step2: [: step 2 ]
    ~SubStep1: [print:  ]
    step 2
    
```

##### Logs with different verbose level
* [c0182 log - verbose level v](../../logs/c0182_v)
* [c0182 log - verbose level vv](../../logs/c0182_vv)
* [c0182 log - verbose level vvv](../../logs/c0182_vvv)
* [c0182 log - verbose level vvvv](../../logs/c0182_vvvv)
* [c0182 log - verbose level vvvvv](../../logs/c0182_vvvvv)

##### References
* [Related Chapter](../../flow-controll/c0182)
