---
title: "f0185_vv"
date: 2020-09-18T00:52:03+99:00
draft: false
weight: 11851

---

### Log reference: <no value>

```
    loading [Config]:  ./tests/functests/upconfig.yml
    Main config:
                 Version -> 1.0.0
                  RefDir -> ./tests/functests
                 WorkDir -> cwd
              AbsWorkDir -> /up_project/up
                TaskFile -> f0185
                 Verbose -> vv
              ModuleName -> self
               ShellType -> /bin/sh
           MaxCallLayers -> 8
                 Timeout -> 3600000
     MaxModuelCallLayers -> 256
               EntryTask -> task
    work dir: /up_project/up
    -exec task: task
    loading [Task]:  ./tests/functests/f0185
    module: [self], instance id: [dev], exec profile: []
    Task1: [task ==> task:  ]
    -Step1: [: task ]
    =Task2: [task ==> sub_task_layer1: sub_task_layer1 ]
    --Step1:
    ==Task3: [task/sub_task_layer1 ==> sub_task_layer2: without rescue, the execution will return a non-zero  return code in shell and also report the error
    with rescue, the program will return 0
     ]
    ---Step1: [step1: step 1 ]
    cmd( 1):
    echo """opening file: {{.loopitem}}"""
    
    -
    opening file: item1
    
    -
     .. ok
    cmd( 2):
    echo "hello"|grep "world"
    
    -
    
    -
     .. failed(suppressed if it is not the last step)
    task Finally:
    ---Step1: [close_file: ensure the opened file is closed
     ]
    cmd( 1):
    echo "close the file ....."
    
    -
    close the file .....
    
    -
     .. ok
    . ok
     WARN: [Rescued in task level, but not advised!] - [setting rescue to yes/true to continue is not recommended
    it is advised to locate root cause of the problem, fix it and re-run the task again
    it is the best practice to test the execution in your ci pipeline to eliminate problems rather than dynamically fix using rescue]
    ===Task3: [task/sub_task_layer1/sub_task_layer2 ==> sub_task_layer2: without rescue, the execution will return a non-zero  return code in shell and also report the error
    with rescue, the program will return 0
     ]
    ----Step1: [step1: step 1 ]
    cmd( 1):
    echo """opening file: {{.loopitem}}"""
    
    -
    opening file: item2
    
    -
     .. ok
    cmd( 2):
    echo "hello"|grep "world"
    
    -
    
    -
     .. failed(suppressed if it is not the last step)
    task Finally:
    ----Step1: [close_file: ensure the opened file is closed
     ]
    cmd( 1):
    echo "close the file ....."
    
    -
    close the file .....
    
    -
     .. ok
    . ok
     WARN: [Rescued in task level, but not advised!] - [setting rescue to yes/true to continue is not recommended
    it is advised to locate root cause of the problem, fix it and re-run the task again
    it is the best practice to test the execution in your ci pipeline to eliminate problems rather than dynamically fix using rescue]
     WARN: [Not rescued in task level] - [please assess the panic problem and cause, fix it before re-run the task]
    task finally ->   ERROR: Failed And Not Ignored! [You may want to continue and ignore the error]
    
    
```

##### Logs with different verbose level
* [f0185 log - verbose level v](../../logs/f0185_v)
* [f0185 log - verbose level vv](../../logs/f0185_vv)
* [f0185 log - verbose level vvv](../../logs/f0185_vvv)
* [f0185 log - verbose level vvvv](../../logs/f0185_vvvv)
* [f0185 log - verbose level vvvvv](../../logs/f0185_vvvvv)

##### References
* [Related Chapter](../../flow-controll/f0185)
