---
title: "final step using block"
date: 2020-10-07T00:11:33+1010:00
draft: false
weight: 1920

---

##### It is a option to use the block instead of callee task. How you use it is a style preference


### Demo








[source](https://github.com/upcmd/up/blob/master/tests/functests/c0182.yml)

##### Main task yaml file
```
    tasks:
    - name: task
      task:
      - func: cmd
        desc: step 1
        do:
        - name: print
          cmd: step 1
        - name: panic
        - name: print
          cmd: extra step ......... it will never reach here
        rescue: true
        finally:
        - func: shell
          name: close_file
          desc: |
            ensure the opened file is closed
          do:
          - echo "close the file ....."
      - func: cmd
        desc: step 2
        do:
        - name: print
          cmd: step 2
    
```
##### Main log file
```
    loading [Config]:  ./tests/functests/upconfig.yml
    Main config:
                 Version -> 1.0.0
                  RefDir -> ./tests/functests
                 WorkDir -> cwd
              AbsWorkDir -> /up_project/up
                TaskFile -> c0182
                 Verbose -> vvv
              ModuleName -> self
               ShellType -> /bin/sh
           MaxCallLayers -> 8
                 Timeout -> 3600000
     MaxModuelCallLayers -> 256
               EntryTask -> task
      ModRepoUsernameRef -> 
      ModRepoPasswordRef -> 
    work dir: /up_project/up
    -exec task: task
    loading [Task]:  ./tests/functests/c0182
    module: [self], instance id: [dev], exec profile: []
    profile -  envVars:
    
    (*core.Cache)({
    })
    
    Task1: [task ==> task:  ]
    -Step1: [: step 1 ]
    self: final context exec vars:
    
    (*core.Cache)({
      "up_runtime_task_layer_number": 0
    })
    
    ~SubStep1: [print:  ]
    step 1
    ~SubStep2: [panic:  ]
     WARN: [manual panic] - [manual trigger a panic cmd]
    Step Finally:
    Recovered from: manual trigger a panic cmd
    -Step1: [
    close_fileensure the opened file is closed
    ]
    self: final context exec vars:
    
    (*core.Cache)({
      "up_runtime_task_layer_number": 0,
      "up_runtime_shell_exec_result": (*utils.ExecResult)(<nil>)
    })
    
    cmd( 1):
    echo "close the file ....."
    
    -
    close the file .....
    
    -
     .. ok
    . ok
     WARN: [Rescued in step level, but not advised!] - [setting rescue to yes/true to continue is not recommended
    it is advised to locate root cause of the problem, fix it and re-run the task again
    it is the best practice to test the execution in your ci pipeline to eliminate problems rather than dynamically fix using rescue]
    -Step2: [: step 2 ]
    self: final context exec vars:
    
    (*core.Cache)({
      "last_result": (*utils.ExecResult)({
        Cmd: "echo \"close the file .....\"",
        Code: 0,
        Output: "close the file .....",
        ErrMsg: ""
      }),
      "up_runtime_task_layer_number": 0
    })
    
    ~SubStep1: [print:  ]
    step 2
    
```


##### Logs with different verbose level
* [c0182 log - verbose level v](../../logs/c0182_v)
* [c0182 log - verbose level vv](../../logs/c0182_vv)
* [c0182 log - verbose level vvv](../../logs/c0182_vvvv)
* [c0182 log - verbose level vvvv](../../logs/c0182_vvvv)
* [c0182 log - verbose level vvvvv](../../logs/c0182_vvvvv)

##### Raw logs with different verbose level
* [c0182 raw log - verbose level v](../../reflogs/c0182_v.log)
* [c0182 raw log - verbose level vv](../../reflogs/c0182_vv.log)
* [c0182 raw log - verbose level vvv](../../reflogs/c0182_vvv.log)
* [c0182 raw log - verbose level vvvv](../../reflogs/c0182_vvvv.log)
* [c0182 raw log - verbose level vvvvv](../../reflogs/c0182_vvvvv.log)








### Other references:
* [shell func:](../../quick-start/c0002/)
* [error handling:](../../test-debug/error_handling/)
* [shell step fails:](../../flow-controll/f0171/)
* [shell step fails:](../../flow-controll/c0172/)
